apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
      - name: fitness-container
        image: xelliann/fitness-website:latest
        ports:
        - containerPort: 80
